version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.33
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-246-92-116.eu-west-1.compute.amazonaws.com
            database: d4cbb3hum3fdn
            user: nvjvkfemepofdh
            password: 0bc683201e1d7384ec167522b12744c3070d968246d5bbec282d9ff8d2fce6ea
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "1234:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - /private/var/lib/pgadmin:/var/lib/pgadmin
      - /tmp/servers.json:/servers.json
